In [25]:
import pandas as pd

1. file "blinkit_orders.csv" <br>
-> tạo cột mới order_total_clean (không xoá cột cũ) = quantity*unit_price (các thuộc tính ở file "blinkit_orders_items")
2. file "blinkit_marketing_performance.csv" <br>
-> tạo cột mới roas_clean = revenue_generated/spend (không xoá cột cũ) 
3. file "blinkit_marketing_performance.csv" <br>
-> tạo thêm 1 cột target_mismatch nếu campaign = "New User Discount" và target_audience không phải "New Users".

In [26]:
df_orders = pd.read_csv('blinkit_orders.csv')
df_order_items = pd.read_csv('blinkit_order_items.csv')
df_marketing = pd.read_csv('blinkit_marketing_performance.csv')

1. Order_total_clean

In [27]:
df_order_items['order_total_clean'] = df_order_items['quantity'] * df_order_items['unit_price']
df_revenue_clean = df_order_items[['order_id', 'order_total_clean']]

df_orders_clean = pd.merge(df_orders, df_revenue_clean, on='order_id', how='inner')

df_orders_clean.to_csv('blinkit_orders_clean.csv', index=False)

print("Quy mô ma trận tệp orders mới:", df_orders_clean.shape)
df_orders_clean.head(5)

Quy mô ma trận tệp orders mới: (5000, 11)

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,order_total_clean
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771,1551.09
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534,881.42
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886,1847.68
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917,874.78
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741,1953.10

2. roas_clean

In [28]:
df_marketing['roas_clean'] = df_marketing['revenue_generated'] / df_marketing['spend']

df_marketing.to_csv('blinkit_marketing_performance_clean.csv', index=False)

print("Quy mô ma trận tệp marketing mới:", df_marketing.shape)
df_marketing[['campaign_id', 'spend', 'revenue_generated', 'roas', 'roas_clean']].head(5)

Quy mô ma trận tệp marketing mới: (5400, 12)

   campaign_id    spend  revenue_generated  roas  roas_clean
0       548299  1431.85            4777.75  3.60    3.336767
1       390914  4506.34            6238.11  2.98    1.384296
2       834385  4524.23            2621.00  2.95    0.579325
3       241523  3622.79            2955.00  2.84    0.815670
4       595111  2888.99            8951.81  2.22    3.098595

3. target_mismatch

In [29]:
df_marketing['target_mismatch'] = (df_marketing['campaign_name'] == 'New User Discount') & (df_marketing['target_audience'] != 'New Users')

df_marketing.to_csv('blinkit_marketing_performance_clean.csv', index=False)

print("Quy mô ma trận tệp marketing mới:", df_marketing.shape)
print("\nBảng thống kê tần suất của trường target_mismatch:")
print(df_marketing['target_mismatch'].value_counts())

df_marketing[['campaign_id', 'campaign_name', 'target_audience', 'target_mismatch']].head(5)

Quy mô ma trận tệp marketing mới: (5400, 13)

Bảng thống kê tần suất của trường target_mismatch:
target_mismatch
False    4953
True      447
Name: count, dtype: int64

   campaign_id      campaign_name target_audience  target_mismatch
0       548299  New User Discount         Premium             True
1       390914    Weekend Special        Inactive            False
2       834385     Festival Offer        Inactive            False
3       241523         Flash Sale        Inactive            False
4       595111   Membership Drive       New Users            False